import type { Metadata } from 'next'
import { Geist } from 'next/font/google'
import '@/shared/styles/index.css'
import ClientLayout from './ClientLayout'
import { MuiProvider } from '@/app/providers/MuiProvider'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'GeoHub',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='uk'>
			<MuiProvider>
				<body
					className={`${geistSans.className} antialiased flex flex-col min-h-screen justify-between`}
				>
					<ClientLayout>{children}</ClientLayout>
				</body>
			</MuiProvider>
		</html>
	)
}
